pecify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
call plug#begin('~/.vim/plugged')

Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
" Plug 'junegunn/vim-easy-align'
Plug 'xolox/vim-notes'
Plug 'xolox/vim-misc'

" Any valid git URL is allowed
" Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Multiple Plug commands can be written in a single line using | separators
"Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" Unmanaged plugin (manually installed and updated)
" Plug '~/my-prototype-plugin'

" Initialize plugin system
call plug#end()


" :let g:notes_directories = ['~/GitHub/IVIUPPET/Linuxy']

mods from windows
vmap <leader>y :w! ~/tmp/vitmp<CR>
vmap <leader>d :w! ~/tmp/vitmp<CR>gvd
" added later
nmap <leader>p :r! cat ~/tmp/vitmp<CR>
"
https://askubuntu.com/questions/60200/how-to-copy-data-between-different-instances-of-vim
set wrap
set textwidth=79

inoremap jk <ESC>

